#\u6570\u636E\u5E93
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdata?serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  #\u8BBE\u7F6Eredis\u7F13\u5B58\u6570\u636E\u7EDF\u4E00\u7684\u6709\u6548\u671F
  cache:
    redis:
      time-to-live: 60000