#\u6570\u636E\u5E93\u914D\u7F6E
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lagou?serverTimezone=UTC
    username: root
    password: root
  # thymeleaf\u914D\u7F6E
  thymeleaf:
    cache: false

#mybatis\u914D\u7F6E
mybatis:
  configuration:
    local-cache-scope: statement
    map-underscore-to-camel-case: true
  type-aliases-package: com.lagou.pojo
  mapper-locations: classpath*:/mapper/*.xml

#\u5206\u9875\u63D2\u4EF6
pagehelper:
  helper-dialect: mysql