#\u6570\u636E\u6E90\u914D\u7F6E\uFF0CDriverClass\u65E0\u9700\u518D\u914D\u7F6E\u3002\u56E0\u4E3A\u4F1A\u81EA\u52A8\u914D\u7F6E
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdata?serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:


# mybatis\u914D\u7F6E
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lagou.pojo

